name: Build
on:
  push:
jobs:
  build-mobile-app:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v5
    - name: Build Mobile App
      id: build_mobile_app
      uses: ArtemSBulgakov/buildozer-action@v1.2.0
      with:
        workdir: simple_todo_mobile
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ${{ steps.build_mobile_app.outputs.filename }}
